name: Build and Test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      throttr:
        image: ghcr.io/throttr/throttr:2.1.0-release
        ports:
          - 9000:9000
        options: >-
          --health-cmd "bash -c 'echo > /dev/tcp/localhost/9000'" 
          --health-interval 5s
          --health-timeout 3s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install Yarn
        run: |
          npm install -g yarn

      - name: Install dependencies
        run: |
          yarn install

      - name: Build project
        run: |
          yarn build

      - name: Run tests with coverage report
        run: |
          yarn test:coverage

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Publish
        if: ${{ github.ref_type == 'tag' }}
        run: |
          echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
          npm publish --access public
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
